# Nombre del workflow
name: Primer Workflow

# Cuando se va a ajecutar la accion
# Eventos
on: [push]

# Que vamos a ejecutar
jobs:
  # Nombre del job arbitraria
  build:
    # Donde corre el job
    runs-on: ubuntu-latest
    # Pasos que va a seguir nuestra job (build)
    steps:
      # Si se va a usar pasos encapsulados en otro lado
      - uses: actions/checkout@v3

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8
